steps:
# --- Data Preparation Image ---
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME', '.'] 
  dir: './components/data_preparation'  # Build context: 'data_preparation' component
- name: 'gcr.io/cloud-builders/docker' 
  args: ['push', 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME'] # Push the image to GCR

# --- Fine-Tunning Image ---
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME'
    - '--build-arg'
    - 'KAGGLE_KEY=$_KAGGLE_KEY'  # Warning: Avoid embedding secrets directly 
    - '--build-arg'
    - 'KAGGLE_USERNAME=$_KAGGLE_USERNAME' 
    - '.'
  dir: './components/fine_tunning'  # Build context: 'fine_tunning' component
- name: 'gcr.io/cloud-builders/docker' 
  args: ['push', 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME'] # Push the image to GCR

# --- Pipeline Image ---
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME'
    - '.'
  dir: './components/pipeline' # Build context: 'pipeline' component
- name: 'gcr.io/cloud-builders/docker' 
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME' # Push the image to GCR

# --- Execute Pipeline ---
- name: 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME:$TAG_NAME' 
  dir: './components/pipeline'  # Set working directory for the container
  args: ['python', 'pipeline.py'] # Execute the pipeline script
  env:
    - 'BUCKET_NAME=$_BUCKET_NAME' # Pass environment variables
    - 'BUCKET_URI=$_BUCKET_URI'
