# Submits a Cloud Build job that builds and deploys a flask application.
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME_FINE_TUNE:$TAG_NAME'
  - '--build-arg'
  - 'KAGGLE_KEY=$_KAGGLE_KEY'
  - '--build-arg'
  - 'KAGGLE_USERNAME=$_KAGGLE_USERNAME'
  - '.'
  dir: './components/fine_tunning'
  # secretEnv: ['KAGGLE_KEY'] 
  id: 'FT_A'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$_CONTAINER_IMAGE_NAME_FINE_TUNE:$TAG_NAME'
  id: 'FT_B'
  waitFor: ['FT_A']
# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_ID/secrets/KAGGLE_KEY/versions/1
#     env: 'KAGGLE_KEY'